- name: Running TestAutomationFrameWork with Maven
  run: mvn test -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=false -X

- name: Upload Test Logs
  if: always()
  uses: actions/upload-artifact@v4.4.3
  with:
    name: test-logs
    path: logs/

- name: Upload Screenshots as Artifacts
  if: always()
  uses: actions/upload-artifact@v4.4.3
  with:
    name: screenshots
    path: screenshots/

- name: Upload HTML Report as Artifact
  if: always()
  uses: actions/upload-artifact@v4.4.3
  with:
    name: html-report
    path: report.html  # Make sure this file exists

- name: Upload Execution Status
  run: echo "Test Execution Completed"

- name: Copy Report to gh-pages Folder
  if: always()
  run: |
    mkdir -p public/extent-reports
    cp -R report.html public/extent-reports/
    cp -R screenshots/ public/extent-reports/screenshots/
    ls -l public/extent-reports

- name: Deploy 🚀
  if: always()
  uses: JamesIves/github-pages-deploy-action@v4
  with:
    folder: public/extent-reports/
    token: ${{ secrets.SECRETE1 }}
    clean: true
