name: TestAutomationFrameWork workFlow1

on:
  schedule:
    - cron: '00 18 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Running TestAutomationFrameWork with Maven
        run: mvn test -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=false -X

      - name: Upload Test Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test logs
          path: logs/

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test Reports
          path: reports.html

      - name: Upload Execution Status
        run: echo "Test Execution Completed"
